vim.api.nvim_set_keymap('n', '<leader>ff', '<cmd>Files<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>fg', '<cmd>GitFiles<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>fb', '<cmd>Buffers<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>fu', '<cmd>Snippets<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>fh', '<cmd>History<CR>', {})
